### ISSUE TITLE
Two oqsprovider instances cause test failure

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#160]
**Describe the bug**
When activating two instances of oqsprovider tests fail. This is the OSX-independent follow-on to #132.

**To Reproduce**
1. Activate two oqsprovider instances in openssl.cnf
2. run tests (e.g., ./scripts/runtests.sh`)

**Expected behavior**
Tests pass

**Environment (please complete the following information):**
 - OS: Ubuntu 22
 - OpenSSL version: 3.2.0-dev, 3.1.0
 - Version: 0.5.0-dev

**Comment by levitte** [comment]
> 1. Activate two oqsprovider instances in openssl.cnf

My first reaction is...  Why?

But come to think of it, we do allow this...  we even allow multiple loads of exactly the same provider (same file), and as far as I can imagine, it shouldn't make a difference if there were two instances of the same actual provider, occupying different memory spaces.

However....  what I'm thinking now is that there may be scenarios where, because they share the same properties to be queried when fetching, some cipher methods may come from one of those two provider instances, and some may come from the other, and an export/import dance of key material needs being transferred from one to the other, and as I recall, there were elements of the OQS keys that were kept strictly internal to the OQS provider, which would mean that the receiving end would end up with an incomplete "private" key, and funny things may start happening.

I'm guessing *wildly*, mind you.  `libcrypto`'s internal list of loaded providers doesn't actually change, and queries for operation implementations should always happen in the same order, so of the two OQS providers, the same one should always be found first and queried first, so all successful fetches should always come from the same OQS provider...  I think (unless someone has added a randomizer in that process when I wasn't looking).

That is, unless the OQS provider is doing something funny that gets disrupted when there are two of them in memory...

My curiosity is picked!  I'll see when I can find some (non-work) time for a deeper dive...

**Comment by baentsch** [comment]
> My first reaction is... Why?

Answered by your own statement: In order to trigger

> an export/import dance of key material needs being transferred from one to the other

This indeed triggered/found a bug reported in #148 and #132 -- now fixed by #161.
