### ISSUE TITLE
oqsx_key_fromdata returns success when no private and public are provided

### ISSUE THREAD

**Issue by Martyrshot** [open-quantum-safe/oqs-provider#295]
Hey!

I've been playing with oqs provider. I noticed that in `oqsx_key_fromdata` that if the user screws up and doesn't provide a `priv` and does not provide a `pub` OSSL_PARAM, that success is returned. Would it make more sense to only return `1` if something was successfully imported?

**Comment by baentsch** [comment]
Thanks for the report @Martyrshot . For this function, indeed, it's not sensible to return OK if both parameters are missing. Please feel free to check whether #296 fixes the issue in your eyes. This is mostly due to the fact that this function is used throughout the provider and sets necessary logic for private only, public only, or complete key pairs.

In general, though, if a user is calling a function without parameters properly set thus leading to a no-operation is not something the provider needs (or IMO sensibly ought) to report: The resultant behaviour (of incorrectly called param getters and setters) will become (more) obvious (to the user) later -- then at the actual operation. As an example, should it be considered an error to not pass a bit length param to a key gen initialization? I don't think so: Rationale: A wrong size parameter passed as parameter to a key gen context creation generally cannot be detected as an error (unlike a completely missing parameter). Both user mistakes will become obvious(ly understandable to the user) at the actual key gen operation, though.
