### ISSUE TITLE
Linux x64 binary incorrect

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#395]
The [0.6.0 release](https://github.com/open-quantum-safe/oqs-provider/releases/tag/0.6.0) CI created a way too small Linux x64 binary artifact but I did not have the time before vacation to find the problem, let alone do PR and re-release. It would be nice if someone else would look into this while I'm gone. @thb-sb, you should have all required privileges to replace the binary in the release with a correct one when the bug has been found & fixed.

**Comment by bhess** [comment]
Changing the following

https://github.com/open-quantum-safe/oqs-provider/blob/0ec51eca39d72867f309878f5bb9002f1c3e07fb/.github/workflows/linux.yml#L74

to `cpack -C DebPack` seems to solve the issue.

**Comment by baentsch** [comment]
Thanks for the suggestion, @bhess ! Release binary suitably updated.

**Comment by catharsis71** [comment]
Hello, I attempted to install the 0.60 .deb (X86) and found that it placed the the ``oqsprovider.so`` in ``/usr/lib/ossl-modules/`` instead of ``/usr/lib/x86_64-linux-gnu/ossl-modules``, causing all OpenSSL-linked services to fail to start.  Running ``ln -s ../../ossl-modules/oqsprovider.so`` resolved the issue.  I can't tell if this is the same issue as described here or not.  Should I open a separate issue?

I tried ARM as well and had a similar but different issue, file was placed in ``/opt/install/lib/ossl-modules/oqsprovider.so`` instead of ``/usr/lib/aarch64-linux-gnu/ossl-modules/``

**Comment by baentsch** [comment]
> I can't tell if this is the same issue as described here or not. Should I open a separate issue?

To me it looks like a separate issue (packaging, not building). So please [create a complete bug report](https://github.com/open-quantum-safe/oqs-provider/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=).

**Comment by elderlabs** [comment]
Going to follow up on this here, as filing a full issue requires more information than I was able to retain during my deployment (and redeploying to replicate that data requires more time to setup than I currently have). Building the current "latest" ([e784ed1](https://github.com/open-quantum-safe/oqs-provider/commit/e784ed12c69f0f6a73e185237d4259d566b5ed97)) works, but requires manual copying post-build from `./oqs-provider/build/lib/` into `/usr/lib/x86_64-linux-gnu/ossl-modules/oqsprovider.so` (do note chmod 644 worked for me, as mine built with 700, likely from my umask). 

I was able to replicate @catharsis71 issue in my original attempts to build release 0.6.0 as the provided release installer chose to install the binary in `/usr/lib/ossl-modules/` instead, which `openssl` didn't appear to look for. I should also note, unless I'm mistaken, the lack of full documentation regarding activiation of OQS with openssl (outside of a demo dockerfile I read) led to much additional initial confusion, along with the lack of a provided binary with `liboqs` (though it did note one could be built). While I won't note much about that, I will note the existing package in Debian's SID branch isn't recognised by the provided 0.6.0 installer in the releases. 

In the end, the biggest help for me, which someone else may benefit from, was adding/uncommenting the following to `/etc/ssl/openssl.cnf`:
```
[openssl_init]
providers = provider_sect

[provider_sect]
default = default_sect
oqsprovider = oqsprovider_sect

[default_sect]
activate = 1

[oqsprovider_sect]
activate = 1
```
For me, it was specifically `providers = provider_sect` that was not noted elsewhere. Without that line uncommented, the others did nothing for me at all. While I do appologize that this isn't a separate issue, and builds upon a closed issue, this is the best I can provide for those searching for this solution in the future so that this does not become an [XKCD #979](https://xkcd.com/979)

In the end, once this is admitted into the Debian repositories fully, such things will no longer be an issue, one could presume. I will note, though, that it was odd to see `liboqs` in Debian's SID repo, but not in testing. For those suffering with this same issue, steering clear of that version would be wise for the time being.

Regards to all.

**Comment by baentsch** [comment]
> the lack of full documentation regarding activiation of OQS with openssl 

Hmm, did you read/see [this](https://github.com/open-quantum-safe/oqs-provider/blob/main/USAGE.md)? If so, could you please consider providing a PR improving/completing this documentation?

**Comment by elderlabs** [comment]
Thank you for your prompt reply. I did see that, however, because `providers = provider_sect` was still commented out by default, the rest did nothing. If I find a free moment, I'd be glad to submit a PR. Without the demo files in your other repo, I'd have been entirely lost, thus I am grateful for them.
