### ISSUE TITLE
Guard against wrong CI feedback

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#432]
It seems CI is not always properly reporting erroneous runs -- but may just silently skip running some tests.

This issue is to suggest guarding against such errors, e.g. by ensuring that always a certain number of CI tests must have been successfully executed. Is something like this possible? Feedback (and ideally, PR) welcome!

**Comment by dstebila** [comment]
Interesting... and annoying. Can we do a study of a few examples and see what patterns if any emerge?  For example:

- Are we not capturing / propagating error return codes correctly? (I seem to recall this being a mistake of ours in the past.)
- Are we getting green checks in PRs when they should be red because some jobs have failed?  
- Is it silently skipping some jobs?  Or some tasks within jobs?
- Are tests being missed on only certain types of runs?  e.g. pushes that aren't PRs, or something like that?

I worry that counting the number of passes might be tricky since the number of jobs run might vary depending on conditions.

Can also ask @ryjones if he's seen other projects that have had problems with CI not reporting correctly.
