### ISSUE TITLE
Add more hybrid algorithms via generate.yml

### ISSUE THREAD

**Issue by maroueneboubakri** [open-quantum-safe/oqs-provider#463]
Hello,

Can the team please 'demystify' the use of `generate.yml` to generate more hybrid algorithms ? Assume I want to add more classical algorithm to combine with dilitium3 or mldsa44, or simply support all EC curves (P-256, P384 and P-521).  

Thank you !
Maro

**Comment by baentsch** [comment]
The classic/PQ "combination logic" driven by "generate.yml" originally was not meant to be used to permit creation of arbitrary PQ-classic algorithm combinations. If that works, as I think it should for arbitrary KEM hybrids (using the tag "hybrid_group") and SIG composites (using the tag "composite" -- tagging @feventura to confirm this statement is true), this is not documented because the ability to "configure in" such combinations (either hybrid or composite) is not a "topline" (hence not documented) `oqsprovider` feature.

If you'd like to have this, please, by all means, provide a documentation+CI PR for it, and if detecting problems (e.g., for hybrid SIGs), most likely the PR also needs to change the logic in `generate.py`.

**Comment by SWilson4** [comment]
Do we actually want to enable creation of arbitrary combinations?  It seems to me that the current list of supported hybrids/composites is curated to match algorithms of similar strength. I could see somebody wanting to be conservative with PQ crypto (e.g., by using Dilithium5 with P-256), but I'm having a hard time imagining a use case where somebody ought to combine a weaker PQ scheme with a stronger group-based one (e.g., Falcon-512 with P-521).

**Comment by maroueneboubakri** [comment]
Understood, thank you !

Br
Maro

**Comment by baentsch** [comment]
> Do we actually want to enable creation of arbitrary combinations? It seems to me that the current list of supported hybrids/composites is curated to match algorithms of similar strength.

Fair question. But the latter statement no longer holds and the reason why we initially (already!) broke this "algorithm strength match rule" was to support/interoperate with other PQ implementations doing this (Cloudflare and Google using L1 x25519 + L3 Kyber768, if memory serves).

So, if someone has a compelling reason for a generalization of this (and definitely, if developing and contributing it) I wouldn't reject this outright but first look at the rationale: So, by all means, don't be discouraged @maroueneboubakri but please let us know what's the rationale for having such "alternative" combinations.
